// Code generated by go-swagger; DO NOT EDIT.

// Package restapi pizza-with-swag
//
//  Schemes:
//    http
//    https
//  Host: srini.tech
//  BasePath: /v1
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
