// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "title": "pizza-with-swag",
    "version": "1.0.0"
  },
  "host": "srini.tech",
  "basePath": "/v1",
  "paths": {
    "/menu": {
      "get": {
        "description": "It returns a list of nested objects which contains all categories and sub-categories required to create menu",
        "tags": [
          "menu"
        ],
        "summary": "Get list of your favourite pizzas",
        "operationId": "ComboList",
        "responses": {
          "200": {
            "description": "List of Offers",
            "schema": {
              "$ref": "#/definitions/Combos"
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "404": {
            "description": "Categories Not Found"
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Combos": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Pizza"
      }
    },
    "Pizza": {
      "type": "object",
      "properties": {
        "bcIsActive": {
          "type": "boolean"
        },
        "pizzaId": {
          "type": "integer"
        },
        "pizzaImageUrl": {
          "type": "string"
        },
        "pizzaName": {
          "type": "string"
        },
        "pizzaPrice": {
          "type": "number"
        },
        "pizzaSize": {
          "type": "integer"
        },
        "toppings": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Topping"
          }
        }
      }
    },
    "Topping": {
      "type": "object",
      "properties": {
        "ToppingName": {
          "type": "string"
        },
        "toppingId": {
          "type": "integer"
        },
        "toppingImageUrl": {
          "type": "string"
        },
        "toppingIsActive": {
          "type": "boolean"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "title": "pizza-with-swag",
    "version": "1.0.0"
  },
  "host": "srini.tech",
  "basePath": "/v1",
  "paths": {
    "/menu": {
      "get": {
        "description": "It returns a list of nested objects which contains all categories and sub-categories required to create menu",
        "tags": [
          "menu"
        ],
        "summary": "Get list of your favourite pizzas",
        "operationId": "ComboList",
        "responses": {
          "200": {
            "description": "List of Offers",
            "schema": {
              "$ref": "#/definitions/Combos"
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "404": {
            "description": "Categories Not Found"
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Combos": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Pizza"
      }
    },
    "Pizza": {
      "type": "object",
      "properties": {
        "bcIsActive": {
          "type": "boolean"
        },
        "pizzaId": {
          "type": "integer"
        },
        "pizzaImageUrl": {
          "type": "string"
        },
        "pizzaName": {
          "type": "string"
        },
        "pizzaPrice": {
          "type": "number"
        },
        "pizzaSize": {
          "type": "integer"
        },
        "toppings": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Topping"
          }
        }
      }
    },
    "Topping": {
      "type": "object",
      "properties": {
        "ToppingName": {
          "type": "string"
        },
        "toppingId": {
          "type": "integer"
        },
        "toppingImageUrl": {
          "type": "string"
        },
        "toppingIsActive": {
          "type": "boolean"
        }
      }
    }
  }
}`))
}
