// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Pizza pizza
//
// swagger:model Pizza
type Pizza struct {

	// bc is active
	BcIsActive bool `json:"bcIsActive,omitempty"`

	// pizza Id
	PizzaID int64 `json:"pizzaId,omitempty"`

	// pizza image Url
	PizzaImageURL string `json:"pizzaImageUrl,omitempty"`

	// pizza name
	PizzaName string `json:"pizzaName,omitempty"`

	// pizza price
	PizzaPrice float64 `json:"pizzaPrice,omitempty"`

	// pizza size
	PizzaSize int64 `json:"pizzaSize,omitempty"`

	// toppings
	Toppings []*Topping `json:"toppings"`
}

// Validate validates this pizza
func (m *Pizza) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateToppings(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Pizza) validateToppings(formats strfmt.Registry) error {
	if swag.IsZero(m.Toppings) { // not required
		return nil
	}

	for i := 0; i < len(m.Toppings); i++ {
		if swag.IsZero(m.Toppings[i]) { // not required
			continue
		}

		if m.Toppings[i] != nil {
			if err := m.Toppings[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("toppings" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("toppings" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this pizza based on the context it is used
func (m *Pizza) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateToppings(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Pizza) contextValidateToppings(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Toppings); i++ {

		if m.Toppings[i] != nil {
			if err := m.Toppings[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("toppings" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("toppings" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Pizza) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Pizza) UnmarshalBinary(b []byte) error {
	var res Pizza
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
