// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Topping topping
//
// swagger:model Topping
type Topping struct {

	// topping name
	ToppingName string `json:"ToppingName,omitempty"`

	// topping Id
	ToppingID int64 `json:"toppingId,omitempty"`

	// topping image Url
	ToppingImageURL string `json:"toppingImageUrl,omitempty"`

	// topping is active
	ToppingIsActive bool `json:"toppingIsActive,omitempty"`
}

// Validate validates this topping
func (m *Topping) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this topping based on context it is used
func (m *Topping) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Topping) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Topping) UnmarshalBinary(b []byte) error {
	var res Topping
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
